---
- name: Install apache
  ansible.builtin.yum:
    name: httpd
    state: present

- name: Start httpd
  ansible.builtin.service:
    name: httpd
    state: started

- name: Copy index.html
  ansible.builtin.template:
    src: index.j2
    dest: /var/www/html/index.html
