---
- name: Make sure security workshop has password set is set to a correct value
  ansible.builtin.assert:
    that:
      - windows_password is defined
    msg: "windows_password must be set for security automation workshop"

- name: Install required roles
  community.general.ansible_galaxy_install:
    type: role
    name: "{{ item }}"
    dest: ./workshop_specific/roles/
  async: 600
  poll: 0
  loop:
    - 'geerlingguy.repo-epel'
    - 'ansible_security.ids_config'
    - 'ansible_security.ids_install'
  register: required_role_loop_out

- name: Install required roles | Async
  ansible.builtin.async_status:
    jid: "{{ item['ansible_job_id'] }}"
  loop: "{{ required_role_loop_out['results'] }}"
  register: job_result
  until: job_result.finished
  retries: 30
